### ISSUE TITLE
求源码

### ISSUE THREAD

**Issue by riruigit** [kfstorm/weibo-hotwords-archive#1]
你好啊，我想看看你的爬虫代码，这个可以分享吗？你这个是多久爬一次的啊？

**Comment by riruigit** [comment]
我看了一下 ， 你的是每分钟 ，那这样的话，你的ip 不会被封禁吗

**Comment by kfstorm** [comment]
代码在这里https://github.com/kfstorm/weibo-hotwords-crawler 。用cron每分钟跑一次。

一分钟就一个请求，比很多人刷微博都慢，频率不高，应该不会被封的。不过我倒是没有在HTTP header上做伪装，要识别爬虫很容易。

**Comment by riruigit** [comment]
你好，你回复的这个链接网页404了 ，你这个项目是设置了私有了吗？

**Comment by riruigit** [comment]
你好，你这个链接404了。是项目设置了私有了吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kfstorm/weibo-hotwords-archive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月13日(星期天) 中午11:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kfstorm/weibo-hotwords-archive] 求源码 (Issue #1)





 
代码在这里https://github.com/kfstorm/weibo-hotwords-crawler。用cron每分钟跑一次。
 
一分钟就一个请求，很多人刷微博好慢，频率不高，应该不会被封的。不过我倒是没有在HTTP header上做伪装，要识别爬虫很容易。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kfstorm** [comment]
不好意思，刚改了权限。再试试吧。

**Comment by riruigit** [comment]
感谢你的开源。看到你的代码得到了一点启示，我也是了一下不带cookie也能爬取下来，实现分钟级的爬虫应该问题不大了，感谢，谢谢你。
